app = "reverse-image"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[env]
  SUPABASE_URL = "https://bpdgwtzndipaybatzcix.supabase.co"
  SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZGd3dHpuZGlwYXliYXR6Y2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyNzkxNDgsImV4cCI6MjA0Njg1NTE0OH0.Jan2VtasYMgsVXiAhbRdlyDC4ol_Ra9mB_eJ3uqUiKE"

[mounts]
  source="data"
  destination="/data"

[[services]]
  http_checks = []
  internal_port = 5000

  [[services.ports]]
     handlers = ["http"]
     port = "80"
